Algoritmo "circulo"

// Descrição : Calcula a área do circulo.
// Autor(a) : Filipe Nóbrega
// Data atual  : 15/12/2025

Var

raio, area : real

Inicio

escreva("Digite quanto vale o raio do circulo: ")
leia(raio)
escreval("")

area <- pi * (raio^2)

escreval("==========================================")
escreval("")

escreval("A área do circulo é igual à ", area:8:3)

escreval("")
escreval("==========================================")
Fimalgoritmo